---
title: "viability_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(magrittr)
```

Import template and data

```{r}
template <- read_csv('../MTHFR/Viability/templates/OCI2_shMTHFR_Venetoclax_02262020.csv', col_types = cols())

viability_data <- readxl::read_excel('../MTHFR/Viability/raw/raw_OCI2_shMTHFR_Venetoclax_Day3_02262020.xlsx', col_names = FALSE)
colnames(viability_data) <- 1:22

```

Transform and identify viability data

```{r}
viability_data %<>% 
  mutate(row=row_number()) %>% 
  pivot_longer(-row, names_to = "column", values_to = "viability") %>% 
  mutate(column = as.numeric(column)) %>% 
  left_join(template, ., by = c("row","column")) %>% 
  filter(is.na(condition) == FALSE)

```

Stats on viability

```{r}
viability_stats <- 
  viability_data %>% 
  group_by(condition, concentration) %>% 
  summarise(
    mean = mean(viability),
    sd = sd(viability)
  )

conditions_max_mean <- viability_stats %>% #extract viability at the lowest concentration
  group_by(condition) %>% 
  slice(1) %>% #slice outputs the first value of each group after a group_by
  select(condition, "mean_0" = mean)

viability_stats %<>% 
  left_join(conditions_max_mean, by = "condition") %>% 
  mutate(relative_viability = mean/mean_0*100)
```



Plot viability


```{r}
viability_stats %>% 
  ggplot(aes(x = log(concentration), y = relative_viability, col = condition))+
    geom_point() +
    stat_smooth(method = loess, se = FALSE)
    
```

extract IC50

```{r}
get_IC50 <- function(cond, viability_df = viability_stats){
  df <- viability_df %>% 
    filter(condition == cond)
  
  p <- ggplot(df, aes(x = concentration, y = relative_viability))+
      geom_point() +
      stat_smooth(method = loess, se = FALSE)
  
  fit_curve <- ggplot_build(p)$data[[2]] %>% #extract loess fit curve
          select(x,y)
  
  
  IC50 <- fit_curve[which(abs(fit_curve$y - 50) == min(abs(fit_curve$y - 50))),1] #identify closest value from 70 and the corresponding          concentration
  IC50 <- round(IC50, digits = 3)
  return(IC50)
}

get_IC50(cond = "shMTHFR2", viability_df = viability_stats)


IC50s <- tibble(
  condition = viability_stats %>% pull(condition) %>% unique(.))

IC50s %<>%
  mutate(IC50 = map(.x = condition, .f = get_IC50, viability_stats))


get_all_IC50s <- function(){}


```


